### ISSUE TITLE
Custom sorting to plotAbundanceDensity

### ISSUE THREAD

**Issue by antagomir** [microbiome/miaViz#29]
The `plotAbundanceDensity` function works fine but I could not find a way to enforce a custom ordering for the taxa in this plot. 

Example plot:

```
library(miaViz)
data(GlobalPatterns)
tse <- GlobalPatterns
plotAbundanceDensity(tse, abund_values = "relabundance")
```

**Task:** change the order of the taxa in a custom way.

**Proposed solution:** add a new function argument, e.g. `orderTaxaBy` and this could use custom vector matching with `rownames(tse)` or a named `rowData` column.

**Comment by FelixErnst** [comment]
First: The `relabundance` assay is not present from your example.

Second: Since aggregation is done base on `topTaxa`, but internally, it is very hard to validate a new order argument. Instead I would propose an example like this:

```r
top_taxa <- getTopTaxa(tse, 25)
plotAbundanceDensity(tse[rownames(tse) %in% top_taxa,], abund_values = "relabundance")
```

I have also mentioned a few times, that ordering on a TSE is most easily done with the tools available from the base packages, aka order within `[,]`. There is usually no need and secondly it usually not flexible enough and third it is very hard to implement an ordering argument which differs from `descending = TRUE`

Third: I think implementing `order_descending` is worth doing. Values can be `TRUE`, `FALSE` or `NA` do disable sorting. 

Would that do it?

**Comment by antagomir** [comment]
Ordering with base [,] is fine but does not work at the moment. 

The following two examples generate the same row order in the plot:

```
plotAbundanceDensity(tse[c(1,2,3),], abund_values = "counts", n=3)
plotAbundanceDensity(tse[c(3,1,2),], abund_values = "counts", n=3)
``` 

Another shortcoming is that the default argument `n=25` and the above examples fail if `n<25`. I think we will need to add to the implementation `n=min(nrow(object), n)` so that the n argument applies only if the data object has more rows than that.

Yep sorry for the relabundances, was adding the example too fast. More focus next time.

**Comment by antagomir** [comment]
Adding `order_descending` would be good, too.

**Comment by FelixErnst** [comment]
Please try `plotAbundanceDensity(tse[c(3,1,2),], abund_values = "counts", n=3, order_descending = NA)` with code from the `order_descending` branch

**Comment by antagomir** [comment]
Yes it works (except that `n=3` argument is still needed at the moment, otherwise it fails)

**Comment by FelixErnst** [comment]
You sure. It is already the default on the branch

**Comment by antagomir** [comment]
Yes now it works now after pulling and merging all the recent changes.
